// use of string...
// There are two ways to declare a string in c language... char array and string literal...
// The string literal cannot be reassigned to another set of characters whereas, we can reassign to the char array...
// <string.h> header file must be included when using or working with string...

#include<stdio.h>  
#include <string.h>    
int main()
{    
   
   char ch[11]={'j', 'a', 'v', 'a', 't', 'p', 'o', 'i', 'n', 't', '\0'};  // declaring string by char array...   
   char ch2[11]="javatpoint";    // declaring string by string literal...
    
   printf("Char Array Value is: %s\n", ch);    
   printf("String Literal Value is: %s\n", ch2);    

 return 0;    
}    
